# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2022

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'sqllocaldb start mssqllocaldb'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'signkey-ef-datamigrations.snk'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'signkey-ef-datamigrations.snk'
    TargetFolder: './private'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)/test/Extensions.EntityFrameworkCore.DataMigraton.Test/Extensions.EntityFrameworkCore.DataMigraton.Test.csproj'
    arguments: '-c EF22'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)/test/Extensions.EntityFrameworkCore.DataMigraton.Test/Extensions.EntityFrameworkCore.DataMigraton.Test.csproj'
    arguments: '-c EF31'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)/test/Extensions.EntityFrameworkCore.DataMigraton.Test/Extensions.EntityFrameworkCore.DataMigraton.Test.csproj'
    arguments: '-c Release'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: PowerShell@2
  inputs:
    filePath: './tools/build.ps1'
    workingDirectory: './tools'
  displayName: 'Run the build script'
- task: CopyFiles@2
  inputs:
    SourceFolder: './dist/nuget'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
