# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'sqllocaldb start mssqllocaldb'
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'signkey-ef-datamigrations.snk'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'signkey-ef-datamigrations.snk'
    TargetFolder: './private'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './test/Extensions.EntityFramework.DataMigraton.Test/Extensions.EntityFramework.DataMigraton.Test.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: PowerShell@2
  env:
    BUILD_PRERELEASE: '$(Build.Prerelease)'
  inputs:
    filePath: './tools/build-full.ps1'
    workingDirectory: './tools'
  displayName: 'Run the build script'
- task: CopyFiles@2
  inputs:
    SourceFolder: './dist/nuget'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
